# Generated by Django 5.2.6 on 2025-09-29 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_date_time', models.CharField(max_length=100)),
                ('order_number', models.BigIntegerField()),
                ('clp_number', models.BigIntegerField()),
                ('status', models.BooleanField()),
            ],
        ),
    ]
