# Generated by Django 5.2.6 on 2025-10-06 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msil_app', '0002_expectedcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='expectedcount',
            name='expected_count',
            field=models.BigIntegerField(null=True),
        ),
    ]
