# Generated by Django 5.2.6 on 2025-10-06 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msil_app', '0003_expectedcount_expected_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpectedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=100, null=True)),
                ('clp_number', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
