# Generated by Django 5.2.6 on 2025-10-06 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msil_app', '0004_expecteddata'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='expecteddata',
            table='ExpectedData',
        ),
    ]
